baseurl: ''
url: ''
markdown: kramdown
theme: dc-site
author: DC Associados
job: DC Associadosr
title: DC Associados
description: >-
  DC Associados é um escritório de advocacia diferenciado e formado por um time
  cujo propósito é simplificar o direito.
logo: +logo.png
favico: +ico.png
card: 'http://lab.diogorusso.com/dc-site/assets/img/share.png'
email: contatoo@dcassociados.com.br
country: Brasil
region: São Paulo
city: São Paulo
