baseurl: ''
url: ''
markdown: kramdown
theme: dc-site
author: DC Associados
job: DC Associadosr
title: DC Associados
description: 'http://localhost:2222/'
logo: +logo.png
favico: +ico.png
email: contatoo@dcassociados.com.br
country: Brasil
region: São Paulo
city: São Paulo
